name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Check if gradle-wrapper.jar is ignored
      run: |
        if git check-ignore -q gradle/wrapper/gradle-wrapper.jar; then
          echo "gradle-wrapper.jar is being ignored by .gitignore"
          echo "Forcing addition of gradle-wrapper.jar"
          git add -f gradle/wrapper/gradle-wrapper.jar
          git commit -m "Force add gradle-wrapper.jar"
        else
          echo "gradle-wrapper.jar is not being ignored"
        fi
        
    - name: Restore Gradle Wrapper
      run: gradle wrapper
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Build with Gradle
      run: ./gradlew shadowJar